using System.Text;

namespace DotWasm.Bindgen;

/// <summary>Emits typed C# bindings that marshal to/from DotWasm's dynamic component API.</summary>
public sealed class CSharpEmitter
{
    readonly string ns;
    readonly Dictionary<string, WitTypeDef> typeDefs = new();
    readonly HashSet<string> resources = new();
    StringBuilder sb = new();

    public CSharpEmitter(string ns, IEnumerable<WitInterface> interfaces)
    {
        this.ns = ns;
        foreach (var iface in interfaces)
            foreach (var t in iface.Types)
            {
                typeDefs[t.Name] = t;
                if (t is WitResourceDef) resources.Add(t.Name);
            }
    }

    public string Emit(List<WitInterface> interfaces, HashSet<string> exported)
    {
        sb.AppendLine("// <auto-generated> Generated by dotwasm-bindgen. Do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using DotWasm.Runtime;");
        sb.AppendLine("using DotWasm.Runtime.Component;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        EmitSupport();

        foreach (var t in typeDefs.Values)
        {
            switch (t)
            {
                case WitRecord r: EmitRecord(r); break;
                case WitVariant v: EmitVariant(v); break;
                case WitEnum e: EmitEnum(e); break;
                case WitFlags f: EmitFlags(f); break;
            }
        }

        EmitMarshal();

        foreach (var iface in interfaces)
            EmitInterface(iface);

        EmitRawListHelpers();

        return sb.ToString();
    }

    // ---- support ----

    void EmitSupport()
    {
        sb.AppendLine("""
        public readonly struct Unit { public static readonly Unit Value = default; }

        public readonly record struct Result<TOk, TErr>(bool IsOk, TOk? Ok, TErr? Err)
        {
            public static Result<TOk, TErr> Okay(TOk v) => new(true, v, default);
            public static Result<TOk, TErr> Error(TErr e) => new(false, default, e);
        }

        """);
    }

    // ---- type emission ----

    void EmitRecord(WitRecord r)
    {
        var fields = string.Join(", ", r.Fields.Select(f => $"{CsType(f.Type)} {Pascal(f.Field)}"));
        sb.AppendLine($"public sealed record {Pascal(r.Name)}({fields});");
        sb.AppendLine();
    }

    void EmitVariant(WitVariant v)
    {
        var baseName = Pascal(v.Name);
        sb.AppendLine($"public abstract record {baseName}");
        sb.AppendLine("{");
        foreach (var (c, t) in v.Cases)
            sb.AppendLine(t is null
                ? $"    public sealed record {Pascal(c)}() : {baseName};"
                : $"    public sealed record {Pascal(c)}({CsType(t)} Value) : {baseName};");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    void EmitEnum(WitEnum e)
    {
        sb.AppendLine($"public enum {Pascal(e.Name)} {{ {string.Join(", ", e.Cases.Select(Pascal))} }}");
        sb.AppendLine();
    }

    void EmitFlags(WitFlags f)
    {
        sb.AppendLine("[Flags]");
        sb.Append($"public enum {Pascal(f.Name)} {{ None = 0");
        for (var i = 0; i < f.Names.Count; i++)
            sb.Append($", {Pascal(f.Names[i])} = {1 << i}");
        sb.AppendLine(" }");
        sb.AppendLine();
    }

    // ---- marshalling helpers (generic + per-named-type) ----

    void EmitMarshal()
    {
        sb.AppendLine("internal static class Marshal");
        sb.AppendLine("{");
        sb.AppendLine("""
            public static object?[] LowerList<T>(T[] a, Func<T, object?> f)
            { var r = new object?[a.Length]; for (int i = 0; i < a.Length; i++) r[i] = f(a[i]); return r; }
            public static T[] LiftList<T>(object? v, Func<object?, T> f)
            { var a = (object?[])v!; var r = new T[a.Length]; for (int i = 0; i < a.Length; i++) r[i] = f(a[i]); return r; }
            public static OptionValue LowerOptionVal<T>(T? v, Func<T, object?> f) where T : struct
                => v.HasValue ? OptionValue.Some(f(v.Value)) : OptionValue.None;
            public static OptionValue LowerOptionRef<T>(T? v, Func<T, object?> f) where T : class
                => v is null ? OptionValue.None : OptionValue.Some(f(v));
            public static T? LiftOptionVal<T>(object? v, Func<object?, T> f) where T : struct
                { var o = (OptionValue)v!; return o.HasValue ? f(o.Value) : default(T?); }
            public static T? LiftOptionRef<T>(object? v, Func<object?, T> f) where T : class
                { var o = (OptionValue)v!; return o.HasValue ? f(o.Value) : null; }
            public static ResultValue LowerResult<TOk, TErr>(Result<TOk, TErr> r, Func<TOk, object?> okf, Func<TErr, object?> errf)
                => r.IsOk ? ResultValue.Ok(okf(r.Ok!)) : ResultValue.Err(errf(r.Err!));
            public static Result<TOk, TErr> LiftResult<TOk, TErr>(object? v, Func<object?, TOk> okf, Func<object?, TErr> errf)
                { var rv = (ResultValue)v!; return rv.IsOk ? Result<TOk, TErr>.Okay(okf(rv.Value)) : Result<TOk, TErr>.Error(errf(rv.Value)); }
        """);
        sb.AppendLine();

        foreach (var t in typeDefs.Values)
        {
            switch (t)
            {
                case WitRecord r: EmitRecordMarshal(r); break;
                case WitVariant v: EmitVariantMarshal(v); break;
                case WitEnum e: EmitEnumMarshal(e); break;
                case WitFlags f: EmitFlagsMarshal(f); break;
            }
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    void EmitRecordMarshal(WitRecord r)
    {
        var name = Pascal(r.Name);
        var lows = string.Join(", ", r.Fields.Select(f => Lower($"v.{Pascal(f.Field)}", f.Type)));
        sb.AppendLine($"    public static object? Lower{name}({name} v) => new object?[] {{ {lows} }};");
        var lifts = string.Join(", ", r.Fields.Select((f, i) => Lift($"a[{i}]", f.Type)));
        sb.AppendLine($"    public static {name} Lift{name}(object? v) {{ var a = (object?[])v!; return new {name}({lifts}); }}");
    }

    void EmitVariantMarshal(WitVariant v)
    {
        var name = Pascal(v.Name);
        sb.AppendLine($"    public static object? Lower{name}({name} v) => v switch");
        sb.AppendLine("    {");
        for (var i = 0; i < v.Cases.Count; i++)
        {
            var (c, t) = v.Cases[i];
            var payload = t is null ? "null" : Lower("c.Value", t);
            sb.AppendLine($"        {name}.{Pascal(c)} c => new VariantValue({i}, {payload}),");
        }
        sb.AppendLine("        _ => throw new ArgumentException(\"bad variant\"),");
        sb.AppendLine("    };");
        sb.AppendLine($"    public static {name} Lift{name}(object? v) {{ var vv = (VariantValue)v!; return (int)vv.Case switch");
        sb.AppendLine("    {");
        for (var i = 0; i < v.Cases.Count; i++)
        {
            var (c, t) = v.Cases[i];
            var arg = t is null ? "" : Lift("vv.Payload", t);
            sb.AppendLine($"        {i} => new {name}.{Pascal(c)}({arg}),");
        }
        sb.AppendLine("        _ => throw new ArgumentException(\"bad variant case\"),");
        sb.AppendLine("    }; }");
    }

    void EmitEnumMarshal(WitEnum e)
    {
        var name = Pascal(e.Name);
        sb.AppendLine($"    public static object? Lower{name}({name} v) => (uint)v;");
        sb.AppendLine($"    public static {name} Lift{name}(object? v) => ({name})(uint)v!;");
    }

    void EmitFlagsMarshal(WitFlags f)
    {
        var name = Pascal(f.Name);
        var lows = string.Join(", ", f.Names.Select(n => $"v.HasFlag({name}.{Pascal(n)})"));
        sb.AppendLine($"    public static object? Lower{name}({name} v) => new FlagsValue(new[] {{ {lows} }});");
        sb.AppendLine($"    public static {name} Lift{name}(object? v) {{ var b = ((FlagsValue)v!).Values; {name} r = 0;");
        for (var i = 0; i < f.Names.Count; i++)
            sb.AppendLine($"        if (b[{i}]) r |= {name}.{Pascal(f.Names[i])};");
        sb.AppendLine($"        return r; }}");
    }

    // ---- interface + resource emission ----

    // wasmName -> cached field name, per interface class
    readonly Dictionary<string, string> funcFields = new();

    /// <summary>Lazily-cached access to a ComponentFunc, avoiding a dictionary lookup per call.</summary>
    string FnAccess(string wasmName)
    {
        if (!funcFields.TryGetValue(wasmName, out var field))
        {
            field = "_f_" + new string(wasmName.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());
            funcFields[wasmName] = field;
        }
        return $"({field} ??= _inst.GetFunc(\"{wasmName}\"))";
    }

    void EmitInterface(WitInterface iface)
    {
        var cls = Pascal(iface.Name);
        funcFields.Clear();
        sb.AppendLine($"public sealed class {cls}");
        sb.AppendLine("{");
        sb.AppendLine("    readonly ComponentSubInstance _inst;");
        sb.AppendLine($"    public {cls}(ComponentSubInstance inst) => _inst = inst;");
        sb.AppendLine($"    public {cls}(ComponentInstance root) => _inst = root.GetInstance(\"{iface.ExportName}\")!;");
        sb.AppendLine();

        // Emit method bodies into a temporary buffer so the cached fields they discover can be
        // declared at the top of the class.
        var outer = sb;
        var body = new StringBuilder();
        sb = body;

        foreach (var fn in iface.Funcs.Where(f => f.Kind is WitFuncKind.Free or WitFuncKind.Static))
            EmitCall(fn, fn.Name, null);

        foreach (var t in iface.Types.OfType<WitResourceDef>())
            foreach (var ctor in t.Methods.Where(m => m.Kind == WitFuncKind.Constructor))
                EmitResourceFactory(t, ctor);

        sb = outer;
        foreach (var field in funcFields.Values)
            sb.AppendLine($"    ComponentFunc? {field};");
        sb.AppendLine();
        sb.Append(body);

        sb.AppendLine("}");
        sb.AppendLine();

        foreach (var t in iface.Types.OfType<WitResourceDef>())
            EmitResourceClass(t);
    }

    void EmitCall(WitFunc fn, string wasmName, string? selfArg)
    {
        // Zero-box raw path when no resource handle is involved and all types are marshallable
        // without boxing; otherwise the proven dynamic (object?) path.
        var eligible = selfArg is null
            && fn.Params.All(p => IsZeroBox(p.Type))
            && (fn.Result is null || IsZeroBox(fn.Result));
        if (eligible)
            EmitCallRaw(fn, wasmName);
        else
            EmitCallDynamic(fn, wasmName, selfArg);
    }

    void EmitCallDynamic(WitFunc fn, string wasmName, string? selfArg)
    {
        var ret = fn.Result is null ? "void" : CsType(fn.Result);
        var ps = string.Join(", ", fn.Params.Select(p => $"{CsType(p.Type)} {Camel(p.Name)}"));
        var argList = (selfArg is null ? Enumerable.Empty<string>() : [$"(object?){selfArg}"])
            .Concat(fn.Params.Select(p => $"(object?)({Lower(Camel(p.Name), p.Type)})"));
        var argArray = $"new object?[] {{ {string.Join(", ", argList)} }}";
        // Resource methods (selfArg != null) live on a per-handle class and call via the
        // sub-instance; free funcs use the interface's lazily-cached ComponentFunc.
        var call = selfArg is null
            ? $"{FnAccess(wasmName)}.Call({argArray})"
            : $"_inst.Invoke(\"{wasmName}\", {string.Join(", ", argList)})";
        sb.AppendLine($"    public {ret} {Pascal(fn.Name)}({ps})");
        sb.AppendLine("    {");
        if (fn.Result is null) sb.AppendLine($"        {call};");
        else { sb.AppendLine($"        var __r = {call};"); sb.AppendLine($"        return {Lift("__r[0]", fn.Result)};"); }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // ================= zero-box raw marshalling =================

    int tmp;
    readonly HashSet<string> listElemKeys = new();
    readonly List<WitType> listElemTypes = new();

    string Tmp() => $"__t{tmp++}";

    bool IsZeroBox(WitType type)
    {
        var t = Resolve(type);
        return t switch
        {
            WitPrim => true,
            WitList l => Resolve(l.Element) is WitPrim,           // primitive-element lists only
            WitTuple tup => tup.Items.All(IsZeroBox),
            WitNamed n when typeDefs.TryGetValue(n.Name, out var d) => d switch
            {
                WitRecord r => r.Fields.All(f => IsZeroBox(f.Type)),
                WitEnum or WitFlags => true,
                _ => false,                                       // variant, resource
            },
            _ => false,                                           // option, result, handle
        };
    }

    int FlatCount(WitType type)
    {
        var t = Resolve(type);
        return t switch
        {
            WitPrim p => p.Kind == "string" ? 2 : 1,
            WitList => 2,
            WitTuple tup => tup.Items.Sum(FlatCount),
            WitNamed n when typeDefs.TryGetValue(n.Name, out var d) && d is WitRecord r => r.Fields.Sum(f => FlatCount(f.Type)),
            _ => 1, // enum/flags
        };
    }

    static int AlignTo(int a, int al) => (a + al - 1) & ~(al - 1);
    static int DiscSize(int cases) => cases <= 256 ? 1 : cases <= 65536 ? 2 : 4;

    int Size(WitType type)
    {
        var t = Resolve(type);
        switch (t)
        {
            case WitPrim p: return PrimSize(p.Kind);
            case WitList: return 8;
            case WitTuple tup: return RecordSize(tup.Items);
            case WitNamed n when typeDefs.TryGetValue(n.Name, out var d):
                return d switch
                {
                    WitRecord r => RecordSize(r.Fields.Select(f => f.Type)),
                    WitEnum e => DiscSize(e.Cases.Count),
                    WitFlags f => FlagsSize(f.Names.Count),
                    _ => 4,
                };
            default: return 4;
        }
    }

    int Align(WitType type)
    {
        var t = Resolve(type);
        switch (t)
        {
            case WitPrim p: return PrimAlign(p.Kind);
            case WitList: return 4;
            case WitTuple tup: return tup.Items.Select(Align).DefaultIfEmpty(1).Max();
            case WitNamed n when typeDefs.TryGetValue(n.Name, out var d):
                return d switch
                {
                    WitRecord r => r.Fields.Select(f => Align(f.Type)).DefaultIfEmpty(1).Max(),
                    WitEnum e => DiscSize(e.Cases.Count),
                    WitFlags f => FlagsSize(f.Names.Count),
                    _ => 4,
                };
            default: return 4;
        }
    }

    int RecordSize(IEnumerable<WitType> fields)
    {
        var s = 0;
        var maxAlign = 1;
        foreach (var f in fields)
        {
            s = AlignTo(s, Align(f));
            s += Size(f);
            maxAlign = Math.Max(maxAlign, Align(f));
        }
        return AlignTo(s, maxAlign);
    }

    static int PrimSize(string k) => k switch
    {
        "bool" or "s8" or "u8" => 1, "s16" or "u16" => 2,
        "s32" or "u32" or "f32" or "char" => 4, "s64" or "u64" or "f64" => 8,
        "string" => 8, _ => 4,
    };
    static int PrimAlign(string k) => k switch
    {
        "bool" or "s8" or "u8" => 1, "s16" or "u16" => 2,
        "s32" or "u32" or "f32" or "char" or "string" => 4, "s64" or "u64" or "f64" => 8, _ => 4,
    };
    static int FlagsSize(int n) => n <= 8 ? 1 : n <= 16 ? 2 : 4;

    void EmitCallRaw(WitFunc fn, string wasmName)
    {
        var ret = fn.Result is null ? "void" : CsType(fn.Result);
        var ps = string.Join(", ", fn.Params.Select(p => $"{CsType(p.Type)} {Camel(p.Name)}"));
        var flatParam = fn.Params.Sum(p => FlatCount(p.Type));
        var paramsIndirect = flatParam > 16;
        var flatResult = fn.Result is null ? 0 : FlatCount(fn.Result);
        var resultsIndirect = flatResult > 1;
        var argCount = paramsIndirect ? 1 : flatParam;
        var resCount = resultsIndirect ? 1 : flatResult;

        sb.AppendLine($"    public {ret} {Pascal(fn.Name)}({ps})");
        sb.AppendLine("    {");
        sb.AppendLine($"        var __fn = {FnAccess(wasmName)};");
        sb.AppendLine("        var __cx = __fn.CreateContext();");
        sb.AppendLine($"        var __args = ArrayPool<WasmValue>.Shared.Rent({Math.Max(1, argCount)});");
        sb.AppendLine($"        var __res = ArrayPool<WasmValue>.Shared.Rent({Math.Max(1, resCount)});");
        sb.AppendLine("        try");
        sb.AppendLine("        {");

        if (paramsIndirect)
        {
            var tupleTypes = fn.Params.Select(p => p.Type).ToList();
            sb.AppendLine($"            int __p = __cx.Allocate({RecordSize(tupleTypes)}, {tupleTypes.Select(Align).DefaultIfEmpty(1).Max()});");
            var off = 0;
            foreach (var p in fn.Params)
            {
                off = AlignTo(off, Align(p.Type));
                StoreMem($"__p + {off}", Camel(p.Name), p.Type);
                off += Size(p.Type);
            }
            sb.AppendLine("            __args[0] = WasmValue.FromI32(__p);");
        }
        else
        {
            sb.AppendLine("            int __i = 0;");
            foreach (var p in fn.Params)
                PushFlat("__args", "__i", Camel(p.Name), p.Type);
        }

        sb.AppendLine($"            __fn.CallCore(__args.AsSpan(0, {argCount}), __res.AsSpan(0, {resCount}));");

        if (fn.Result is not null)
        {
            if (resultsIndirect)
            {
                sb.AppendLine("            int __rp = __res[0].I32;");
                sb.AppendLine($"            var __r = {LoadMem("__rp", fn.Result)};");
            }
            else
            {
                sb.AppendLine("            int __ri = 0;");
                sb.AppendLine($"            var __r = {ReadFlat("__res", "__ri", fn.Result)};");
            }
        }

        sb.AppendLine($"            __fn.Finish(__cx, __res.AsSpan(0, {resCount}));");
        if (fn.Result is not null) sb.AppendLine("            return __r;");

        sb.AppendLine("        }");
        sb.AppendLine("        finally");
        sb.AppendLine("        {");
        sb.AppendLine("            ArrayPool<WasmValue>.Shared.Return(__args);");
        sb.AppendLine("            ArrayPool<WasmValue>.Shared.Return(__res);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    void PushFlat(string buf, string idx, string expr, WitType type)
    {
        var t = Resolve(type);
        switch (t)
        {
            case WitPrim p:
                switch (p.Kind)
                {
                    case "bool": sb.AppendLine($"            {buf}[{idx}++] = WasmValue.FromI32({expr} ? 1 : 0);"); break;
                    case "s8": case "s16": case "s32": sb.AppendLine($"            {buf}[{idx}++] = WasmValue.FromI32((int){expr});"); break;
                    case "u8": case "u16": sb.AppendLine($"            {buf}[{idx}++] = WasmValue.FromI32({expr});"); break;
                    case "u32": sb.AppendLine($"            {buf}[{idx}++] = WasmValue.FromI32(unchecked((int){expr}));"); break;
                    case "char": sb.AppendLine($"            {buf}[{idx}++] = WasmValue.FromI32({expr});"); break;
                    case "s64": sb.AppendLine($"            {buf}[{idx}++] = WasmValue.FromI64({expr});"); break;
                    case "u64": sb.AppendLine($"            {buf}[{idx}++] = WasmValue.FromI64(unchecked((long){expr}));"); break;
                    case "f32": sb.AppendLine($"            {buf}[{idx}++] = WasmValue.FromF32({expr});"); break;
                    case "f64": sb.AppendLine($"            {buf}[{idx}++] = WasmValue.FromF64({expr});"); break;
                    case "string":
                        var ts = Tmp();
                        sb.AppendLine($"            var {ts} = __cx.StoreStringRange({expr});");
                        sb.AppendLine($"            {buf}[{idx}++] = WasmValue.FromI32({ts}.Ptr);");
                        sb.AppendLine($"            {buf}[{idx}++] = WasmValue.FromI32({ts}.CodeUnits);");
                        break;
                }
                break;
            case WitList l:
                var tl = Tmp();
                sb.AppendLine($"            var {tl} = {ListStore(expr, l.Element)};");
                sb.AppendLine($"            {buf}[{idx}++] = WasmValue.FromI32({tl}.Item1);");
                sb.AppendLine($"            {buf}[{idx}++] = WasmValue.FromI32({tl}.Item2);");
                break;
            case WitTuple tup:
                for (var i = 0; i < tup.Items.Count; i++)
                    PushFlat(buf, idx, $"{expr}.Item{i + 1}", tup.Items[i]);
                break;
            case WitNamed n when typeDefs.TryGetValue(n.Name, out var d) && d is WitRecord r:
                foreach (var f in r.Fields) PushFlat(buf, idx, $"{expr}.{Pascal(f.Field)}", f.Type);
                break;
            case WitNamed when t is WitNamed: // enum or flags
                sb.AppendLine($"            {buf}[{idx}++] = WasmValue.FromI32(unchecked((int)(uint){expr}));");
                break;
        }
    }

    string ReadFlat(string buf, string idx, WitType type)
    {
        var t = Resolve(type);
        switch (t)
        {
            case WitPrim p:
                return p.Kind switch
                {
                    "bool" => $"({buf}[{idx}++].I32 != 0)",
                    "s8" => $"(sbyte){buf}[{idx}++].I32",
                    "u8" => $"(byte){buf}[{idx}++].I32",
                    "s16" => $"(short){buf}[{idx}++].I32",
                    "u16" => $"(ushort){buf}[{idx}++].I32",
                    "s32" or "char" => $"{buf}[{idx}++].I32",
                    "u32" => $"(uint){buf}[{idx}++].I32",
                    "s64" => $"{buf}[{idx}++].I64",
                    "u64" => $"(ulong){buf}[{idx}++].I64",
                    "f32" => $"{buf}[{idx}++].F32",
                    "f64" => $"{buf}[{idx}++].F64",
                    _ => $"{buf}[{idx}++].I32",
                };
            case WitTuple tup:
                return $"({string.Join(", ", tup.Items.Select(it => ReadFlat(buf, idx, it)))})";
            case WitNamed n when typeDefs.TryGetValue(n.Name, out var d) && d is WitRecord r:
                return $"new {Pascal(n.Name)}({string.Join(", ", r.Fields.Select(f => ReadFlat(buf, idx, f.Type)))})";
            case WitNamed n2 when typeDefs.TryGetValue(n2.Name, out var d2) && d2 is WitFlags:
                return $"({Pascal(n2.Name)}){buf}[{idx}++].I32";
            case WitNamed n3:
                return $"({Pascal(n3.Name)})(uint){buf}[{idx}++].I32"; // enum
            default:
                return $"{buf}[{idx}++].I32";
        }
    }

    void StoreMem(string ptr, string expr, WitType type)
    {
        var t = Resolve(type);
        switch (t)
        {
            case WitPrim p:
                sb.AppendLine($"            {StorePrim(ptr, expr, p.Kind)};");
                break;
            case WitList l:
                var tl = Tmp();
                sb.AppendLine($"            var {tl} = {ListStore(expr, l.Element)};");
                sb.AppendLine($"            __cx.StoreS32({ptr}, {tl}.Item1);");
                sb.AppendLine($"            __cx.StoreS32(({ptr}) + 4, {tl}.Item2);");
                break;
            case WitTuple tup:
            {
                var off = 0;
                for (var i = 0; i < tup.Items.Count; i++)
                {
                    off = AlignTo(off, Align(tup.Items[i]));
                    StoreMem($"({ptr}) + {off}", $"{expr}.Item{i + 1}", tup.Items[i]);
                    off += Size(tup.Items[i]);
                }
                break;
            }
            case WitNamed n when typeDefs.TryGetValue(n.Name, out var d) && d is WitRecord r:
            {
                var off = 0;
                foreach (var f in r.Fields)
                {
                    off = AlignTo(off, Align(f.Type));
                    StoreMem($"({ptr}) + {off}", $"{expr}.{Pascal(f.Field)}", f.Type);
                    off += Size(f.Type);
                }
                break;
            }
            case WitNamed n2 when typeDefs.TryGetValue(n2.Name, out var d2) && d2 is WitEnum e:
                sb.AppendLine($"            {StoreInt(ptr, $"(uint){expr}", DiscSize(e.Cases.Count))};");
                break;
            case WitNamed n3 when typeDefs.TryGetValue(n3.Name, out var d3) && d3 is WitFlags f3:
                sb.AppendLine($"            {StoreInt(ptr, $"(uint){expr}", FlagsSize(f3.Names.Count))};");
                break;
        }
    }

    static string StorePrim(string ptr, string expr, string kind) => kind switch
    {
        "bool" => $"__cx.StoreBool({ptr}, {expr})",
        "s8" => $"__cx.StoreS8({ptr}, {expr})",
        "u8" => $"__cx.StoreU8({ptr}, {expr})",
        "s16" => $"__cx.StoreS16({ptr}, {expr})",
        "u16" => $"__cx.StoreU16({ptr}, {expr})",
        "s32" => $"__cx.StoreS32({ptr}, {expr})",
        "u32" => $"__cx.StoreU32({ptr}, {expr})",
        "s64" => $"__cx.StoreS64({ptr}, {expr})",
        "u64" => $"__cx.StoreU64({ptr}, {expr})",
        "f32" => $"__cx.StoreF32({ptr}, {expr})",
        "f64" => $"__cx.StoreF64({ptr}, {expr})",
        "char" => $"__cx.StoreChar({ptr}, {expr})",
        "string" => $"__cx.StoreStringAt({ptr}, {expr})",
        _ => $"__cx.StoreS32({ptr}, (int){expr})",
    };

    static string StoreInt(string ptr, string expr, int size) => size switch
    {
        1 => $"__cx.StoreU8({ptr}, (byte)({expr}))",
        2 => $"__cx.StoreU16({ptr}, (ushort)({expr}))",
        _ => $"__cx.StoreU32({ptr}, (uint)({expr}))",
    };

    static string LoadInt(string ptr, int size) => size switch
    {
        1 => $"__cx.LoadU8({ptr})",
        2 => $"__cx.LoadU16({ptr})",
        _ => $"__cx.LoadU32({ptr})",
    };

    string LoadMem(string ptr, WitType type)
    {
        var t = Resolve(type);
        switch (t)
        {
            case WitPrim p:
                return p.Kind switch
                {
                    "bool" => $"__cx.LoadBool({ptr})",
                    "s8" => $"__cx.LoadS8({ptr})",
                    "u8" => $"__cx.LoadU8({ptr})",
                    "s16" => $"__cx.LoadS16({ptr})",
                    "u16" => $"__cx.LoadU16({ptr})",
                    "s32" => $"__cx.LoadS32({ptr})",
                    "u32" => $"__cx.LoadU32({ptr})",
                    "s64" => $"__cx.LoadS64({ptr})",
                    "u64" => $"__cx.LoadU64({ptr})",
                    "f32" => $"__cx.LoadF32({ptr})",
                    "f64" => $"__cx.LoadF64({ptr})",
                    "char" => $"__cx.LoadChar({ptr})",
                    "string" => $"__cx.LoadStringAt({ptr})",
                    _ => $"__cx.LoadS32({ptr})",
                };
            case WitList l:
                return $"{ListLoad(ptr, l.Element)}";
            case WitTuple tup:
            {
                var parts = new List<string>();
                var off = 0;
                foreach (var it in tup.Items)
                {
                    off = AlignTo(off, Align(it));
                    parts.Add(LoadMem($"({ptr}) + {off}", it));
                    off += Size(it);
                }
                return $"({string.Join(", ", parts)})";
            }
            case WitNamed n when typeDefs.TryGetValue(n.Name, out var d) && d is WitRecord r:
            {
                var parts = new List<string>();
                var off = 0;
                foreach (var f in r.Fields)
                {
                    off = AlignTo(off, Align(f.Type));
                    parts.Add(LoadMem($"({ptr}) + {off}", f.Type));
                    off += Size(f.Type);
                }
                return $"new {Pascal(n.Name)}({string.Join(", ", parts)})";
            }
            case WitNamed n2 when typeDefs.TryGetValue(n2.Name, out var d2) && d2 is WitEnum e:
                return $"({Pascal(n2.Name)})(int){LoadInt(ptr, DiscSize(e.Cases.Count))}";
            case WitNamed n3 when typeDefs.TryGetValue(n3.Name, out var d3) && d3 is WitFlags f3:
                return $"({Pascal(n3.Name)})(int){LoadInt(ptr, FlagsSize(f3.Names.Count))}";
            default:
                return $"__cx.LoadS32({ptr})";
        }
    }

    string ElemKey(WitType elem) => CsType(elem).Replace("[]", "Arr").Replace(".", "_").Replace("?", "N").Replace("(", "T").Replace(")", "").Replace(", ", "_").Replace(" ", "");

    string ListStore(string expr, WitType elem)
    {
        RegisterListHelper(elem);
        return $"RawList.Store_{ElemKey(elem)}(__cx, {expr})";
    }

    string ListLoad(string ptr, WitType elem)
    {
        RegisterListHelper(elem);
        return $"RawList.Load_{ElemKey(elem)}(__cx, {ptr})";
    }

    void RegisterListHelper(WitType elem)
    {
        if (listElemKeys.Add(ElemKey(elem)))
            listElemTypes.Add(elem);
    }

    void EmitRawListHelpers()
    {
        if (listElemTypes.Count == 0) return;
        sb.AppendLine("internal static class RawList");
        sb.AppendLine("{");
        foreach (var elem in listElemTypes)
        {
            var key = ElemKey(elem);
            var cs = CsType(elem);
            var esize = Size(elem);
            var ealign = Align(elem);
            sb.AppendLine($"    public static (int, int) Store_{key}(CanonContext __cx, {cs}[] v)");
            sb.AppendLine("    {");
            sb.AppendLine($"        int __d = __cx.Allocate(v.Length * {esize}, {ealign});");
            sb.AppendLine("        for (int k = 0; k < v.Length; k++)");
            sb.AppendLine("        {");
            StoreMem($"__d + k * {esize}", "v[k]", elem);
            sb.AppendLine("        }");
            sb.AppendLine("        return (__d, v.Length);");
            sb.AppendLine("    }");
            sb.AppendLine($"    public static {cs}[] Load_{key}(CanonContext __cx, int ptr)");
            sb.AppendLine("    {");
            sb.AppendLine("        int __d = __cx.LoadS32(ptr); int __n = __cx.LoadS32(ptr + 4);");
            sb.AppendLine($"        var a = new {cs}[__n];");
            sb.AppendLine("        for (int k = 0; k < __n; k++)");
            sb.AppendLine($"            a[k] = {LoadMem($"__d + k * {esize}", elem)};");
            sb.AppendLine("        return a;");
            sb.AppendLine("    }");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    void EmitResourceFactory(WitResourceDef res, WitFunc ctor)
    {
        var cls = Pascal(res.Name);
        var ps = string.Join(", ", ctor.Params.Select(p => $"{CsType(p.Type)} {Camel(p.Name)}"));
        var args = string.Join(", ", ctor.Params.Select(p => $"(object?)({Lower(Camel(p.Name), p.Type)})"));
        sb.AppendLine($"    public {cls} New{cls}({ps})");
        sb.AppendLine("    {");
        sb.AppendLine($"        var __r = {FnAccess($"[constructor]{res.Name}")}.Call(new object?[] {{ {args} }});");
        sb.AppendLine($"        return new {cls}((ResourceValue)__r[0]!, _inst);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    void EmitResourceClass(WitResourceDef res)
    {
        var cls = Pascal(res.Name);
        sb.AppendLine($"public sealed class {cls}");
        sb.AppendLine("{");
        sb.AppendLine("    readonly ResourceValue _h;");
        sb.AppendLine("    readonly ComponentSubInstance _inst;");
        sb.AppendLine($"    internal {cls}(ResourceValue h, ComponentSubInstance inst) {{ _h = h; _inst = inst; }}");
        sb.AppendLine("    public ResourceValue Handle => _h;");
        sb.AppendLine();
        foreach (var m in res.Methods.Where(m => m.Kind == WitFuncKind.Method))
            EmitCall(m, $"[method]{res.Name}.{m.Name}", "_h");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ---- C# type mapping ----

    WitType Resolve(WitType t)
    {
        while (t is WitNamed n && typeDefs.TryGetValue(n.Name, out var d) && d is WitAlias a)
            t = a.Target;
        return t;
    }

    string CsType(WitType type)
    {
        var t = Resolve(type);
        return t switch
        {
            WitPrim p => PrimCs(p.Kind),
            WitList l => $"{CsType(l.Element)}[]",
            WitOption o => $"{CsType(o.Inner)}?",
            WitResult r => $"Result<{(r.Ok is null ? "Unit" : CsType(r.Ok))}, {(r.Err is null ? "Unit" : CsType(r.Err))}>",
            WitTuple tup => $"({string.Join(", ", tup.Items.Select(CsType))})",
            WitHandle h => Pascal(h.Resource),
            WitNamed n => Pascal(n.Name),
            _ => "object?",
        };
    }

    static string PrimCs(string k) => k switch
    {
        "bool" => "bool", "s8" => "sbyte", "u8" => "byte", "s16" => "short", "u16" => "ushort",
        "s32" => "int", "u32" => "uint", "s64" => "long", "u64" => "ulong",
        "f32" => "float", "f64" => "double", "char" => "int", "string" => "string",
        _ => "object?",
    };

    bool IsRef(WitType type)
    {
        var t = Resolve(type);
        return t switch
        {
            WitPrim p => p.Kind == "string",
            WitList or WitOption or WitHandle => true,
            WitNamed n => typeDefs.TryGetValue(n.Name, out var d) && d is WitRecord or WitVariant or WitResourceDef,
            _ => false,
        };
    }

    // ---- marshalling expressions ----

    string Lower(string expr, WitType type)
    {
        var t = Resolve(type);
        switch (t)
        {
            case WitPrim: return expr;
            case WitList l: return $"Marshal.LowerList({expr}, __x => {Lower("__x", l.Element)})";
            case WitOption o:
            {
                var helper = IsRef(o.Inner) ? "LowerOptionRef" : "LowerOptionVal";
                return $"Marshal.{helper}({expr}, __o => {Lower("__o", o.Inner)})";
            }
            case WitResult r:
            {
                var okf = r.Ok is null ? "__o => null" : $"__o => {Lower("__o", r.Ok)}";
                var errf = r.Err is null ? "__e => null" : $"__e => {Lower("__e", r.Err)}";
                return $"Marshal.LowerResult({expr}, {okf}, {errf})";
            }
            case WitTuple tup:
                return $"new object?[] {{ {string.Join(", ", tup.Items.Select((it, i) => Lower($"{expr}.Item{i + 1}", it)))} }}";
            case WitHandle: return $"{expr}.Handle";
            case WitNamed n when resources.Contains(n.Name): return $"{expr}.Handle";
            case WitNamed n: return $"Marshal.Lower{Pascal(n.Name)}({expr})";
            default: return expr;
        }
    }

    string Lift(string expr, WitType type)
    {
        var t = Resolve(type);
        switch (t)
        {
            case WitPrim p when p.Kind == "string": return $"(string){expr}!";
            case WitPrim p: return $"({PrimCs(p.Kind)}){expr}!";
            case WitList l: return $"Marshal.LiftList<{CsType(l.Element)}>({expr}, __o => {Lift("__o", l.Element)})";
            case WitOption o:
            {
                var helper = IsRef(o.Inner) ? "LiftOptionRef" : "LiftOptionVal";
                return $"Marshal.{helper}<{CsType(o.Inner)}>({expr}, __o => {Lift("__o", o.Inner)})";
            }
            case WitResult r:
            {
                var okT = r.Ok is null ? "Unit" : CsType(r.Ok);
                var errT = r.Err is null ? "Unit" : CsType(r.Err);
                var okf = r.Ok is null ? "__o => Unit.Value" : $"__o => {Lift("__o", r.Ok)}";
                var errf = r.Err is null ? "__e => Unit.Value" : $"__e => {Lift("__e", r.Err)}";
                return $"Marshal.LiftResult<{okT}, {errT}>({expr}, {okf}, {errf})";
            }
            case WitTuple tup:
                return $"({string.Join(", ", tup.Items.Select((it, i) => Lift($"((object?[]){expr}!)[{i}]", it)))})";
            case WitHandle h: return $"new {Pascal(h.Resource)}((ResourceValue){expr}!, _inst)";
            case WitNamed n when resources.Contains(n.Name): return $"new {Pascal(n.Name)}((ResourceValue){expr}!, _inst)";
            case WitNamed n: return $"Marshal.Lift{Pascal(n.Name)}({expr})";
            default: return expr;
        }
    }

    // ---- naming ----

    public static string Pascal(string kebab) =>
        string.Concat(kebab.Split('-', '_').Where(p => p.Length > 0).Select(p => char.ToUpperInvariant(p[0]) + p[1..]));

    public static string Camel(string kebab)
    {
        var p = Pascal(kebab);
        var c = p.Length > 0 ? char.ToLowerInvariant(p[0]) + p[1..] : p;
        return CsKeywords.Contains(c) ? "@" + c : c;
    }

    static readonly HashSet<string> CsKeywords = new()
    {
        "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const",
        "continue","decimal","default","delegate","do","double","else","enum","event","explicit","extern",
        "false","finally","fixed","float","for","foreach","goto","if","implicit","in","int","interface",
        "internal","is","lock","long","namespace","new","null","object","operator","out","override","params",
        "private","protected","public","readonly","ref","return","sbyte","sealed","short","sizeof","stackalloc",
        "static","string","struct","switch","this","throw","true","try","typeof","uint","ulong","unchecked",
        "unsafe","ushort","using","virtual","void","volatile","while",
    };
}
