using System.Text;

namespace DotWasm.Bindgen;

/// <summary>Emits typed C# bindings that marshal to/from DotWasm's dynamic component API.</summary>
public sealed class CSharpEmitter
{
    readonly string ns;
    readonly Dictionary<string, WitTypeDef> typeDefs = new();
    readonly HashSet<string> resources = new();
    readonly StringBuilder sb = new();

    public CSharpEmitter(string ns, IEnumerable<WitInterface> interfaces)
    {
        this.ns = ns;
        foreach (var iface in interfaces)
            foreach (var t in iface.Types)
            {
                typeDefs[t.Name] = t;
                if (t is WitResourceDef) resources.Add(t.Name);
            }
    }

    public string Emit(List<WitInterface> interfaces, HashSet<string> exported)
    {
        sb.AppendLine("// <auto-generated> Generated by dotwasm-bindgen. Do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using DotWasm.Runtime.Component;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        EmitSupport();

        foreach (var t in typeDefs.Values)
        {
            switch (t)
            {
                case WitRecord r: EmitRecord(r); break;
                case WitVariant v: EmitVariant(v); break;
                case WitEnum e: EmitEnum(e); break;
                case WitFlags f: EmitFlags(f); break;
            }
        }

        EmitMarshal();

        foreach (var iface in interfaces)
            EmitInterface(iface);

        return sb.ToString();
    }

    // ---- support ----

    void EmitSupport()
    {
        sb.AppendLine("""
        public readonly struct Unit { public static readonly Unit Value = default; }

        public readonly record struct Result<TOk, TErr>(bool IsOk, TOk? Ok, TErr? Err)
        {
            public static Result<TOk, TErr> Okay(TOk v) => new(true, v, default);
            public static Result<TOk, TErr> Error(TErr e) => new(false, default, e);
        }

        """);
    }

    // ---- type emission ----

    void EmitRecord(WitRecord r)
    {
        var fields = string.Join(", ", r.Fields.Select(f => $"{CsType(f.Type)} {Pascal(f.Field)}"));
        sb.AppendLine($"public sealed record {Pascal(r.Name)}({fields});");
        sb.AppendLine();
    }

    void EmitVariant(WitVariant v)
    {
        var baseName = Pascal(v.Name);
        sb.AppendLine($"public abstract record {baseName}");
        sb.AppendLine("{");
        foreach (var (c, t) in v.Cases)
            sb.AppendLine(t is null
                ? $"    public sealed record {Pascal(c)}() : {baseName};"
                : $"    public sealed record {Pascal(c)}({CsType(t)} Value) : {baseName};");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    void EmitEnum(WitEnum e)
    {
        sb.AppendLine($"public enum {Pascal(e.Name)} {{ {string.Join(", ", e.Cases.Select(Pascal))} }}");
        sb.AppendLine();
    }

    void EmitFlags(WitFlags f)
    {
        sb.AppendLine("[Flags]");
        sb.Append($"public enum {Pascal(f.Name)} {{ None = 0");
        for (var i = 0; i < f.Names.Count; i++)
            sb.Append($", {Pascal(f.Names[i])} = {1 << i}");
        sb.AppendLine(" }");
        sb.AppendLine();
    }

    // ---- marshalling helpers (generic + per-named-type) ----

    void EmitMarshal()
    {
        sb.AppendLine("internal static class Marshal");
        sb.AppendLine("{");
        sb.AppendLine("""
            public static object?[] LowerList<T>(T[] a, Func<T, object?> f)
            { var r = new object?[a.Length]; for (int i = 0; i < a.Length; i++) r[i] = f(a[i]); return r; }
            public static T[] LiftList<T>(object? v, Func<object?, T> f)
            { var a = (object?[])v!; var r = new T[a.Length]; for (int i = 0; i < a.Length; i++) r[i] = f(a[i]); return r; }
            public static OptionValue LowerOptionVal<T>(T? v, Func<T, object?> f) where T : struct
                => v.HasValue ? OptionValue.Some(f(v.Value)) : OptionValue.None;
            public static OptionValue LowerOptionRef<T>(T? v, Func<T, object?> f) where T : class
                => v is null ? OptionValue.None : OptionValue.Some(f(v));
            public static T? LiftOptionVal<T>(object? v, Func<object?, T> f) where T : struct
                { var o = (OptionValue)v!; return o.HasValue ? f(o.Value) : default(T?); }
            public static T? LiftOptionRef<T>(object? v, Func<object?, T> f) where T : class
                { var o = (OptionValue)v!; return o.HasValue ? f(o.Value) : null; }
            public static ResultValue LowerResult<TOk, TErr>(Result<TOk, TErr> r, Func<TOk, object?> okf, Func<TErr, object?> errf)
                => r.IsOk ? ResultValue.Ok(okf(r.Ok!)) : ResultValue.Err(errf(r.Err!));
            public static Result<TOk, TErr> LiftResult<TOk, TErr>(object? v, Func<object?, TOk> okf, Func<object?, TErr> errf)
                { var rv = (ResultValue)v!; return rv.IsOk ? Result<TOk, TErr>.Okay(okf(rv.Value)) : Result<TOk, TErr>.Error(errf(rv.Value)); }
        """);
        sb.AppendLine();

        foreach (var t in typeDefs.Values)
        {
            switch (t)
            {
                case WitRecord r: EmitRecordMarshal(r); break;
                case WitVariant v: EmitVariantMarshal(v); break;
                case WitEnum e: EmitEnumMarshal(e); break;
                case WitFlags f: EmitFlagsMarshal(f); break;
            }
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    void EmitRecordMarshal(WitRecord r)
    {
        var name = Pascal(r.Name);
        var lows = string.Join(", ", r.Fields.Select(f => Lower($"v.{Pascal(f.Field)}", f.Type)));
        sb.AppendLine($"    public static object? Lower{name}({name} v) => new object?[] {{ {lows} }};");
        var lifts = string.Join(", ", r.Fields.Select((f, i) => Lift($"a[{i}]", f.Type)));
        sb.AppendLine($"    public static {name} Lift{name}(object? v) {{ var a = (object?[])v!; return new {name}({lifts}); }}");
    }

    void EmitVariantMarshal(WitVariant v)
    {
        var name = Pascal(v.Name);
        sb.AppendLine($"    public static object? Lower{name}({name} v) => v switch");
        sb.AppendLine("    {");
        for (var i = 0; i < v.Cases.Count; i++)
        {
            var (c, t) = v.Cases[i];
            var payload = t is null ? "null" : Lower("c.Value", t);
            sb.AppendLine($"        {name}.{Pascal(c)} c => new VariantValue({i}, {payload}),");
        }
        sb.AppendLine("        _ => throw new ArgumentException(\"bad variant\"),");
        sb.AppendLine("    };");
        sb.AppendLine($"    public static {name} Lift{name}(object? v) {{ var vv = (VariantValue)v!; return (int)vv.Case switch");
        sb.AppendLine("    {");
        for (var i = 0; i < v.Cases.Count; i++)
        {
            var (c, t) = v.Cases[i];
            var arg = t is null ? "" : Lift("vv.Payload", t);
            sb.AppendLine($"        {i} => new {name}.{Pascal(c)}({arg}),");
        }
        sb.AppendLine("        _ => throw new ArgumentException(\"bad variant case\"),");
        sb.AppendLine("    }; }");
    }

    void EmitEnumMarshal(WitEnum e)
    {
        var name = Pascal(e.Name);
        sb.AppendLine($"    public static object? Lower{name}({name} v) => (uint)v;");
        sb.AppendLine($"    public static {name} Lift{name}(object? v) => ({name})(uint)v!;");
    }

    void EmitFlagsMarshal(WitFlags f)
    {
        var name = Pascal(f.Name);
        var lows = string.Join(", ", f.Names.Select(n => $"v.HasFlag({name}.{Pascal(n)})"));
        sb.AppendLine($"    public static object? Lower{name}({name} v) => new FlagsValue(new[] {{ {lows} }});");
        sb.AppendLine($"    public static {name} Lift{name}(object? v) {{ var b = ((FlagsValue)v!).Values; {name} r = 0;");
        for (var i = 0; i < f.Names.Count; i++)
            sb.AppendLine($"        if (b[{i}]) r |= {name}.{Pascal(f.Names[i])};");
        sb.AppendLine($"        return r; }}");
    }

    // ---- interface + resource emission ----

    void EmitInterface(WitInterface iface)
    {
        var cls = Pascal(iface.Name);
        sb.AppendLine($"public sealed class {cls}");
        sb.AppendLine("{");
        sb.AppendLine("    readonly ComponentSubInstance _inst;");
        sb.AppendLine($"    public {cls}(ComponentSubInstance inst) => _inst = inst;");
        sb.AppendLine($"    public {cls}(ComponentInstance root) => _inst = root.GetInstance(\"{iface.ExportName}\")!;");
        sb.AppendLine();

        foreach (var fn in iface.Funcs.Where(f => f.Kind is WitFuncKind.Free or WitFuncKind.Static))
            EmitCall(fn, fn.Name, null);

        foreach (var t in iface.Types.OfType<WitResourceDef>())
            foreach (var ctor in t.Methods.Where(m => m.Kind == WitFuncKind.Constructor))
                EmitResourceFactory(t, ctor);

        sb.AppendLine("}");
        sb.AppendLine();

        foreach (var t in iface.Types.OfType<WitResourceDef>())
            EmitResourceClass(t);
    }

    void EmitCall(WitFunc fn, string wasmName, string? selfArg)
    {
        var ret = fn.Result is null ? "void" : CsType(fn.Result);
        var ps = string.Join(", ", fn.Params.Select(p => $"{CsType(p.Type)} {Camel(p.Name)}"));
        // Cast each arg to object? so Invoke's params array never spreads a lowered list/record.
        var argList = (selfArg is null ? Enumerable.Empty<string>() : [$"(object?){selfArg}"])
            .Concat(fn.Params.Select(p => $"(object?)({Lower(Camel(p.Name), p.Type)})"));
        var args = string.Join(", ", argList);
        var call = $"_inst.Invoke(\"{wasmName}\"{(args.Length > 0 ? ", " + args : "")})";
        sb.AppendLine($"    public {ret} {Pascal(fn.Name)}({ps})");
        sb.AppendLine("    {");
        if (fn.Result is null) sb.AppendLine($"        {call};");
        else { sb.AppendLine($"        var __r = {call};"); sb.AppendLine($"        return {Lift("__r[0]", fn.Result)};"); }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    void EmitResourceFactory(WitResourceDef res, WitFunc ctor)
    {
        var cls = Pascal(res.Name);
        var ps = string.Join(", ", ctor.Params.Select(p => $"{CsType(p.Type)} {Camel(p.Name)}"));
        var args = string.Join(", ", ctor.Params.Select(p => $"(object?)({Lower(Camel(p.Name), p.Type)})"));
        sb.AppendLine($"    public {cls} New{cls}({ps})");
        sb.AppendLine("    {");
        sb.AppendLine($"        var __r = _inst.Invoke(\"[constructor]{res.Name}\"{(args.Length > 0 ? ", " + args : "")});");
        sb.AppendLine($"        return new {cls}((ResourceValue)__r[0]!, _inst);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    void EmitResourceClass(WitResourceDef res)
    {
        var cls = Pascal(res.Name);
        sb.AppendLine($"public sealed class {cls}");
        sb.AppendLine("{");
        sb.AppendLine("    readonly ResourceValue _h;");
        sb.AppendLine("    readonly ComponentSubInstance _inst;");
        sb.AppendLine($"    internal {cls}(ResourceValue h, ComponentSubInstance inst) {{ _h = h; _inst = inst; }}");
        sb.AppendLine("    public ResourceValue Handle => _h;");
        sb.AppendLine();
        foreach (var m in res.Methods.Where(m => m.Kind == WitFuncKind.Method))
            EmitCall(m, $"[method]{res.Name}.{m.Name}", "_h");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ---- C# type mapping ----

    WitType Resolve(WitType t)
    {
        while (t is WitNamed n && typeDefs.TryGetValue(n.Name, out var d) && d is WitAlias a)
            t = a.Target;
        return t;
    }

    string CsType(WitType type)
    {
        var t = Resolve(type);
        return t switch
        {
            WitPrim p => PrimCs(p.Kind),
            WitList l => $"{CsType(l.Element)}[]",
            WitOption o => $"{CsType(o.Inner)}?",
            WitResult r => $"Result<{(r.Ok is null ? "Unit" : CsType(r.Ok))}, {(r.Err is null ? "Unit" : CsType(r.Err))}>",
            WitTuple tup => $"({string.Join(", ", tup.Items.Select(CsType))})",
            WitHandle h => Pascal(h.Resource),
            WitNamed n => Pascal(n.Name),
            _ => "object?",
        };
    }

    static string PrimCs(string k) => k switch
    {
        "bool" => "bool", "s8" => "sbyte", "u8" => "byte", "s16" => "short", "u16" => "ushort",
        "s32" => "int", "u32" => "uint", "s64" => "long", "u64" => "ulong",
        "f32" => "float", "f64" => "double", "char" => "int", "string" => "string",
        _ => "object?",
    };

    bool IsRef(WitType type)
    {
        var t = Resolve(type);
        return t switch
        {
            WitPrim p => p.Kind == "string",
            WitList or WitOption or WitHandle => true,
            WitNamed n => typeDefs.TryGetValue(n.Name, out var d) && d is WitRecord or WitVariant or WitResourceDef,
            _ => false,
        };
    }

    // ---- marshalling expressions ----

    string Lower(string expr, WitType type)
    {
        var t = Resolve(type);
        switch (t)
        {
            case WitPrim: return expr;
            case WitList l: return $"Marshal.LowerList({expr}, __x => {Lower("__x", l.Element)})";
            case WitOption o:
            {
                var helper = IsRef(o.Inner) ? "LowerOptionRef" : "LowerOptionVal";
                return $"Marshal.{helper}({expr}, __o => {Lower("__o", o.Inner)})";
            }
            case WitResult r:
            {
                var okf = r.Ok is null ? "__o => null" : $"__o => {Lower("__o", r.Ok)}";
                var errf = r.Err is null ? "__e => null" : $"__e => {Lower("__e", r.Err)}";
                return $"Marshal.LowerResult({expr}, {okf}, {errf})";
            }
            case WitTuple tup:
                return $"new object?[] {{ {string.Join(", ", tup.Items.Select((it, i) => Lower($"{expr}.Item{i + 1}", it)))} }}";
            case WitHandle: return $"{expr}.Handle";
            case WitNamed n when resources.Contains(n.Name): return $"{expr}.Handle";
            case WitNamed n: return $"Marshal.Lower{Pascal(n.Name)}({expr})";
            default: return expr;
        }
    }

    string Lift(string expr, WitType type)
    {
        var t = Resolve(type);
        switch (t)
        {
            case WitPrim p when p.Kind == "string": return $"(string){expr}!";
            case WitPrim p: return $"({PrimCs(p.Kind)}){expr}!";
            case WitList l: return $"Marshal.LiftList<{CsType(l.Element)}>({expr}, __o => {Lift("__o", l.Element)})";
            case WitOption o:
            {
                var helper = IsRef(o.Inner) ? "LiftOptionRef" : "LiftOptionVal";
                return $"Marshal.{helper}<{CsType(o.Inner)}>({expr}, __o => {Lift("__o", o.Inner)})";
            }
            case WitResult r:
            {
                var okT = r.Ok is null ? "Unit" : CsType(r.Ok);
                var errT = r.Err is null ? "Unit" : CsType(r.Err);
                var okf = r.Ok is null ? "__o => Unit.Value" : $"__o => {Lift("__o", r.Ok)}";
                var errf = r.Err is null ? "__e => Unit.Value" : $"__e => {Lift("__e", r.Err)}";
                return $"Marshal.LiftResult<{okT}, {errT}>({expr}, {okf}, {errf})";
            }
            case WitTuple tup:
                return $"({string.Join(", ", tup.Items.Select((it, i) => Lift($"((object?[]){expr}!)[{i}]", it)))})";
            case WitHandle h: return $"new {Pascal(h.Resource)}((ResourceValue){expr}!, _inst)";
            case WitNamed n when resources.Contains(n.Name): return $"new {Pascal(n.Name)}((ResourceValue){expr}!, _inst)";
            case WitNamed n: return $"Marshal.Lift{Pascal(n.Name)}({expr})";
            default: return expr;
        }
    }

    // ---- naming ----

    public static string Pascal(string kebab) =>
        string.Concat(kebab.Split('-', '_').Where(p => p.Length > 0).Select(p => char.ToUpperInvariant(p[0]) + p[1..]));

    public static string Camel(string kebab)
    {
        var p = Pascal(kebab);
        var c = p.Length > 0 ? char.ToLowerInvariant(p[0]) + p[1..] : p;
        return CsKeywords.Contains(c) ? "@" + c : c;
    }

    static readonly HashSet<string> CsKeywords = new()
    {
        "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const",
        "continue","decimal","default","delegate","do","double","else","enum","event","explicit","extern",
        "false","finally","fixed","float","for","foreach","goto","if","implicit","in","int","interface",
        "internal","is","lock","long","namespace","new","null","object","operator","out","override","params",
        "private","protected","public","readonly","ref","return","sbyte","sealed","short","sizeof","stackalloc",
        "static","string","struct","switch","this","throw","true","try","typeof","uint","ulong","unchecked",
        "unsafe","ushort","using","virtual","void","volatile","while",
    };
}
