using System.Diagnostics;
using System.Text;
using DotWasm.Encoding;
using DotWasm.Runtime;
using SourceGenPoc;

// Modes:
//   gen     -> transpile the benchmark wasm functions to C# (overwrites Generated.cs)
//   verify  -> run interpreter vs generated, assert identical memory output
//   bench   -> verify, then time interpreter vs generated (DotWasm-only, reuse instance)

string mode = args.Length > 0 ? args[0] : "bench";
string Dir() => AppContext.BaseDirectory;
byte[] Wasm(string n) => File.ReadAllBytes(Path.Combine(Dir(), n));

if (mode == "gen")
{
    var gray = WasmEncoding.Decode(Wasm("grayscale_bench.wasm"));
    var coll = WasmEncoding.Decode(Wasm("collatz_bench.wasm"));
    var sb = new StringBuilder();
    sb.AppendLine("namespace SourceGenPoc;");
    sb.AppendLine();
    sb.AppendLine("// AUTO-GENERATED by `dotnet run gen`. Do not edit.");
    sb.AppendLine("internal static class Generated");
    sb.AppendLine("{");
    sb.Append(Transpiler.Transpile(gray, "grayscale_bench", "Grayscale"));
    sb.Append(Transpiler.Transpile(coll, "collatz_bench", "Collatz"));
    sb.AppendLine("}");
    // Write into the source tree (two levels up from bin/Release/netX/).
    var srcPath = Path.GetFullPath(Path.Combine(Dir(), "..", "..", "..", "Generated.cs"));
    File.WriteAllText(srcPath, sb.ToString());
    Console.WriteLine($"Generated -> {srcPath}");
    Console.WriteLine(sb.ToString());
    return;
}

// ---- shared setup ----
const int PixelCount = 128 * 128;
const int ImageBytes = PixelCount * 4;

var grayModule = WasmEncoding.Decode(Wasm("grayscale_bench.wasm"));
var grayInst = new WasmLinker(new WasmStore()).Instantiate(grayModule);
grayInst.TryGetExportedMemory("memory", out var grayMem);

var collModule = WasmEncoding.Decode(Wasm("collatz_bench.wasm"));
var collInst = new WasmLinker(new WasmStore()).Instantiate(collModule);
collInst.TryGetExportedMemory("memory", out var collMem);

byte[] MakeImage()
{
    var src = new byte[ImageBytes];
    var rng = new Random(42);
    rng.NextBytes(src);
    for (var i = 3; i < src.Length; i += 4) src[i] = 255;
    return src;
}

// ---- verify correctness: generated output must byte-match the interpreter ----
{
    // grayscale
    var src = MakeImage();
    src.CopyTo(grayMem!.Data[..ImageBytes]);
    grayInst.Invoke("grayscale_bench", [0, PixelCount], []);
    var interp = grayMem.Data[..ImageBytes].ToArray();

    var genMem = new byte[grayMem.Data.Length];
    src.CopyTo(genMem.AsSpan(0, ImageBytes));
    Generated.Grayscale(genMem, 0, PixelCount);
    if (!interp.AsSpan().SequenceEqual(genMem.AsSpan(0, ImageBytes)))
        throw new Exception("VERIFY FAILED: grayscale generated output != interpreter");

    // collatz
    const int N = 10000;
    collInst.Invoke("collatz_bench", [N], []);
    var interpC = collMem!.Data[..(N * 4)].ToArray();
    var genMemC = new byte[collMem.Data.Length];
    Generated.Collatz(genMemC, N);
    if (!interpC.AsSpan().SequenceEqual(genMemC.AsSpan(0, N * 4)))
        throw new Exception("VERIFY FAILED: collatz generated output != interpreter");

    Console.WriteLine("VERIFY OK: generated output byte-identical to interpreter (grayscale + collatz)");
}

if (mode == "verify") return;

// ---- benchmark ----
double TimeMin(Action a, int iters, int warmup)
{
    for (int i = 0; i < warmup; i++) a();
    double best = double.MaxValue;
    for (int r = 0; r < 5; r++)
    {
        var sw = Stopwatch.StartNew();
        for (int i = 0; i < iters; i++) a();
        sw.Stop();
        best = Math.Min(best, sw.Elapsed.TotalMilliseconds * 1000.0 / iters);
    }
    return best;
}

var image = MakeImage();
var grayGenMem = new byte[grayMem!.Data.Length];

var grayInterp = TimeMin(() =>
{
    image.CopyTo(grayMem.Data[..ImageBytes]);
    grayInst.Invoke("grayscale_bench", [0, PixelCount], []);
}, 3000, 200);

var grayGen = TimeMin(() =>
{
    image.CopyTo(grayGenMem.AsSpan(0, ImageBytes));
    Generated.Grayscale(grayGenMem, 0, PixelCount);
}, 3000, 200);

var collGenMem = new byte[collMem!.Data.Length];
var collInterp = TimeMin(() => collInst.Invoke("collatz_bench", [10000], []), 200, 20);
var collGen = TimeMin(() => Generated.Collatz(collGenMem, 10000), 200, 20);

Console.WriteLine($"grayscale: interpreter {grayInterp:F1} us/call | generated {grayGen:F1} us/call | {grayInterp / grayGen:F1}x");
Console.WriteLine($"collatz:   interpreter {collInterp:F1} us/call | generated {collGen:F1} us/call | {collInterp / collGen:F1}x");
